# Generated by Django 4.0.3 on 2022-05-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='id_formaPagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.formapagamento', verbose_name='Forma de Pagamento'),
        ),
    ]
